// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3BXK21lED6a2x-OCXCWF3u3GBWMM9Is',
    appId: '1:323376431360:web:f3b8792944d2ccc3f2b3e5',
    messagingSenderId: '323376431360',
    projectId: 'ibarber-af73e',
    authDomain: 'ibarber-af73e.firebaseapp.com',
    storageBucket: 'ibarber-af73e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdguvPyJ8JFSdx8SfLUzbZGj3v8a5ZqCU',
    appId: '1:323376431360:android:588fc3b2dd2f84e0f2b3e5',
    messagingSenderId: '323376431360',
    projectId: 'ibarber-af73e',
    storageBucket: 'ibarber-af73e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-boTzBQEL5N3iOP2Q8BswC1XDCAU-oSM',
    appId: '1:323376431360:ios:bcc1d3b195194ef5f2b3e5',
    messagingSenderId: '323376431360',
    projectId: 'ibarber-af73e',
    storageBucket: 'ibarber-af73e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-boTzBQEL5N3iOP2Q8BswC1XDCAU-oSM',
    appId: '1:323376431360:ios:bcc1d3b195194ef5f2b3e5',
    messagingSenderId: '323376431360',
    projectId: 'ibarber-af73e',
    storageBucket: 'ibarber-af73e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX3BXK21lED6a2x-OCXCWF3u3GBWMM9Is',
    appId: '1:323376431360:web:9b3c28ddb5f09a58f2b3e5',
    messagingSenderId: '323376431360',
    projectId: 'ibarber-af73e',
    authDomain: 'ibarber-af73e.firebaseapp.com',
    storageBucket: 'ibarber-af73e.firebasestorage.app',
  );

}